### ISSUE TITLE
Implement oauth2

### ISSUE THREAD

**Issue by iget-master** [spatie/dropbox-api#18]
Should Oauth2 functionality be implemented on this library?

If so, I suggest implementing it from [stevenmaguire/oauth2-dropbox](https://github.com/stevenmaguire/oauth2-dropbox], that I've just made a PR to make it compatible with Dropbox API v2.

If you agree, I can do a PR to implement it when/if @stevenmaguire merge my PR.

**Edit:** oauth2-dropbox is now compatible with v2.

**Comment by freekmurze** [comment]
Thanks for your suggestion. 

I want to keep this package as simple as possible. Unless it can be implemented in a very easy and testable way I'll just stick to providing the common API methods.
