### ISSUE TITLE
Using in conjunction with laravel-backup and flysystem-dropbox

### ISSUE THREAD

**Issue by coryrose1** [spatie/dropbox-api#25]
Hi,

Thanks for releasing these great packages.

I have been able to use [laravel-backup](https://github.com/spatie/laravel-backup) and [flysystem-dropbox ](https://github.com/spatie/flysystem-dropbox) in order to backup my app database to a private Dropbox folder.

Dropbox also has a Business API that allows you to act as a team member with file access. I am interested in using this as it will allow me to backup the DB to my organization's shared business Dropbox folder.

There is more information from Dropbox here: https://www.dropbox.com/developers-v1/business#member-file-access

Specifically:

```
Member file access

Make calls to the Dropbox Core API for any member of the Dropbox Business team. Your app must have Team member file access permission.

To make calls on a member's behalf, use the OAuth token granted to the app by the team. Specify the member_id of the user that the app wants to act on using a custom HTTP header called X-Dropbox-Perform-As-Team-Member.
```

I am wondering if it is possible to use the API package with your laravel-backup and flysystem-Dropbox in order to post files to a shared business folder?

Thank you again!
Cory

**Comment by freekmurze** [comment]
I'm not a user of Dropbox for Business and therefore don't have a need to use the related API methods.

I'd accept fully tested, non-breaking PRs that add new API endpoints.
