### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by wilson382** [spatie/dropbox-api#29]
Somehow when I try to upload a file from the root of the server I get this error.  But it works fine if I upload from web root. 
Parse error: syntax error, unexpected '*', expecting ',' or ';' in /home/user4/cron/dropboxv2/vendor/spatie/dropbox-api/src/Client.php on line 23

**Comment by freekmurze** [comment]
Could you PR a failing test?

**Comment by wilson382** [comment]
I think so. How should I open a new repository for it and share it here?

**Comment by sebastiandedeyne** [comment]
Hey, looks like you're on an older PHP version there. the syntax error is because PHP didn't support scalar expressions in constants before version 5.6.

https://wiki.php.net/rfc/const_scalar_exprs

This package requires PHP 7.0+ to work, so you'll need to upgrade your server for this to work.

**Comment by wilson382** [comment]
I said it doe work if I move the api library to web root but when trying to use from server root like there the cron jobs are placed it gives the parser error.

And I'm using php version 7.0

**Comment by wilson382** [comment]
It's not php version. I'm currently using php 7.0. I also managed to make it work by moving my whole folder to web root but it doesn't work when placed at the server root. I'm trying to run this with an automatic cron job.

**Comment by freekmurze** [comment]
Are you sure you're running PHP 7.0 on the command line as well? Find out php executing a script with a `phpinfo()` and inspect the output.

**Comment by wilson382** [comment]
> Are you sure you're running PHP 7.0 on the command line as well? Find out php executing a script with a phpinfo() and inspect the output.

@freekmurze man you are right. i created a test cron file  which will email me $version=phpversion(); to my email and this is output of $version, PHP Version:  5.4.45.

I didn't know the command line could use different php version than what version is used at the webroot. Is there any work around?
