### ISSUE TITLE
createSharedLinkWithSettings endpoint 

### ISSUE THREAD

**Issue by prafgon** [spatie/dropbox-api#40]
Hi there!

Just letting you know that the "createSharedLinkWithSettings" throws an exception when used without the "settings" parameter, like the following:

`$sharedLink = $dropbox->createSharedLinkWithSettings( $path );`

The exception message from Dropbox:

> Client error: `POST https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings` resulted in a `400 Bad Request` response: Error in call to API function "sharing/create_shared_link_with_settings": request body: settings: expected object, got l (truncated...)

If I add the second, $settings parameter (even though it's optional based on your docs) no exceptions are thrown:

```
$settings = array( 'requested_visibility' => 'public' );
$sharedLink = $dropbox->createSharedLinkWithSettings( $path, $settings );
```

So the thing is that you default the $settings argument (if none is provided) to an empty array in the method declaration:

`public function createSharedLinkWithSettings(string $path, array $settings = [])`

And then use that empty array in the API call parameters:

```
$parameters = [
            'path' => $this->normalizePath($path),
            'settings' => $settings,
        ];
```

So you're actually sending an empty parameter value (instead of not setting it at all).

Just thought I'd report this. Thanks!

**Comment by freekmurze** [comment]
Could you send a PR that fixes this?
