### ISSUE TITLE
List directory recursively not working

### ISSUE THREAD

**Issue by JuanWilde** [spatie/dropbox-api#46]
I have this folder structure
```
CMI/tool/video tool/tested/au/
```
Inside this folder I have 2 more with a couple of videos
```
2017-06/video1.mp4
2017-08/video2.mp4
```

When I run `$this->client->listFolder($path, true);` I only get until `au`, but neither subfolders nor videos.

Any tip will be appreciated. Thanks

**Comment by pryley** [comment]
@JuanWilde It works correctly for me. 

Please see the API documentation for [files/list_folder](https://www.dropbox.com/developers/documentation/http/documentation#files-list_folder), specifically the `has_more` in the response.
