### ISSUE TITLE
Uploading a pdf

### ISSUE THREAD

**Issue by jessequinn** [spatie/dropbox-api#53]
Hi guys,

Great work here, but i am having a small issue.

I want to upload a pdf file and i have tried the following with failure (Badrequest is thrown).

```php
$upload = $client->upload($newFilename, file_get_contents($documentFile->getPathname()));
$upload = $client->upload($newFilename, addslashes(file_get_contents($documentFile->getPathname())));
```

How would i go about uploading a small pdf file?

**Comment by jessequinn** [comment]
`            $upload = $client->upload('/' . $fileName, @$file->getRealPath());
`

**Comment by Nodedrizla** [comment]
Hi @jessequinn, 
Did you manage to upload the file. I am facing similar issue.

**Comment by Nodedrizla** [comment]
> 

$fd = fopen($filePath, "rb");
$res = $this->dropBox->client->upload($path,  $fd);
