### ISSUE TITLE
How to use a proxy?

### ISSUE THREAD

**Issue by xiebruce** [spatie/dropbox-api#54]
How can I use a proxy(like GuzzleHttp)?  Cause Dropbox can't be access in China.

**Comment by atymic** [comment]
The client constructor accepts a custom guzzle client as the second argument:
https://github.com/spatie/dropbox-api/blob/master/src/Client.php#L51-L55

Just configure the client you pass to with a proxy: http://docs.guzzlephp.org/en/stable/request-options.html#proxy

**Comment by xiebruce** [comment]
@atymic It works fine, thank you.

I put my code here in case someone need it:
```
use GuzzleHttp\Client as GuzzleClient;
use Spatie\Dropbox\Client;

// new GuzzleClient
$guzzleClient = new GuzzleClient([
	'timeout'  => 30.0,
	'proxy' => 'http://127.0.0.1:1087',
]);

// new dropbox-api client
$client = new Client($accessToken, $guzzleClient);
$res = $client->upload('test.jpg', fopen($uploadFilePath, 'rb'));
var_dump($res);
```

**Comment by atymic** [comment]
No worries :)
