### ISSUE TITLE
Dropbox-API-Path-Root

### ISSUE THREAD

**Issue by nielsvr** [spatie/dropbox-api#58]
Is it possible with this package to set the Dropbox-API-Path-Root header? You need this to access Team Shared folders. You add a header to your request with the correct namespace_id, example;

`['Dropbox-API-Path-Root' => '{".tag": "namespace_id", "namespace_id": "1234"}' ];`

Can't seem to find a method for this.

**Comment by freekmurze** [comment]
Will be handled in #64
