### ISSUE TITLE
An invalid access token does NOT throw an exception message

### ISSUE THREAD

**Issue by remusnegrota** [spatie/dropbox-api#72]
If you specify an invalid access token an exception IS thrown, but it does NOT contain an error message.

```
....
catch (Exception $e) {
  //this is an empty string
  echo $e->getMessage();
}
```

If you echo just the exception object the following stack trace is shown:

```
Spatie\Dropbox\Exceptions\BadRequest in /var/www/html/dropbox-sdk/vendor/spatie/dropbox-api/src/Client.php:657
Stack trace:
#0 /var/www/html/dropbox-sdk/vendor/spatie/dropbox-api/src/Client.php(629): Spatie\Dropbox\Client->determineException(Object(GuzzleHttp\Exception\ClientException))
#1 /var/www/html/dropbox-sdk/vendor/spatie/dropbox-api/src/Client.php(402): Spatie\Dropbox\Client->contentEndpointRequest('files/upload', Array, Resource id #19)
#2 /var/www/html/dev/dbox-test.php(17): Spatie\Dropbox\Client->upload('/testFolder/tes...', Resource id #19, 'add')
```

Clearly, this does not handle the exception all the way through.

Invalid access tokens can be a common occurrence.

Any idea why this behaves this way and what could be done?

**Comment by jhoff** [comment]
You should be able to get the guzzle response though using `$e->response->getBody()->__toString()`

**Comment by remusnegrota** [comment]
> You should be able to get the guzzle response though using `$e->response->getBody()->__toString()`

Yep this works, thank you.
