### ISSUE TITLE
preparing for short-lived auth tokens

### ISSUE THREAD

**Issue by GDmac** [spatie/dropbox-api#75]
In preparation for dropbox moving to short-lived tokens (mid 2021),
i'ld like to open this issue to keep track of steps i did to with league/oath2-client.
composer require `league/oauth2-client` and `stevenmaguire/oauth2-dropbox`

```php
use Stevenmaguire\OAuth2\Client\Provider\Dropbox;

$authClient = new Dropbox([
    'clientId' => APP_KEY,
    'clientSecret' => APP_SECRET,
    // 'redirectUri'       => '' // no redirect, we want a long lasting offline token
]);

// 1. Setup, one time refresh_token fetch. 
// Open URL in browser, user gives permission, dropbox gives connection code
// https://www.dropbox.com/oauth2/authorize?client_id=[APP_KEY]&response_type=code&token_access_type=offline
echo $authClient->getAuthorizationUrl([
    'token_access_type' => 'offline'
]);

// With the obtained code, fetch an access_token and a long-lasting refresh_token
$token = $authClient->getAccessToken('authorization_code', ['code' => $userCode]);

// 2. Normal use.
// Get token from your tokenStorage, if token->hasExpired() 
// then fetch new token with help from refresh_token (see league oauth2Client page)

// use Spatie dropbox with the access_token and the prepared guzzleClient
$dropbox = new Spatie\Dropbox\Client($token->getToken(), $authClient->getHttpClient());
$dir = $dropbox->listFolder("/Apps/");

print_r($dir);
```

**Comment by GDmac** [comment]
Phpstorm is complaining that the spatie\dropbox constructor expects a `GuzzleClient`,
however the league\oauth2 dropbox `->getHttpClient()` is returning a guzzle `ClientInterface`
https://github.com/spatie/dropbox-api/blob/master/src/Client.php#L61

**Comment by alexkuc** [comment]
I am in the same position myself where Dropbox dropped support for official PHP SDK and existing libraries do not support refresh tokens. I was gonna write my own homebrew library to deal with oauth2 but thanks to @GDmac I now realized there are existing (standalone) oauth2 libraries which can deal with this. Hopefully, I will have time this weekends to look into this too.

**Comment by alexkuc** [comment]
> Phpstorm is complaining that the spatie\dropbox constructor expects a `GuzzleClient`,
> however the league\oauth2 dropbox `->getHttpClient()` is returning a guzzle `ClientInterface`
> https://github.com/spatie/dropbox-api/blob/master/src/Client.php#L61

I assume it is a question about issue with 2nd parameter `$client` so I will provide my understanding here:

- author (@freekmurze) wishes to keep this repo simple so it does *not* deal with any sort of authentication (https://github.com/spatie/dropbox-api/issues/18)
- this package consumes but *does not* handle the authentication i.e. something else needs to deal with token/auth/etc.
- 2nd parameter `$client` (`GuzzleClient`) is used to process API requests e.g. `listFolder()` or `download()`
- authentication is consumed as scalar (meaning it is taken at face value, as-is): 
https://github.com/spatie/dropbox-api/blob/35e5f546bc4c29df34afa7363086dfcfa3448367/src/Client.php#L33-L34
https://github.com/spatie/dropbox-api/blob/35e5f546bc4c29df34afa7363086dfcfa3448367/src/Client.php#L39-L43

I will send a working example in a moment which uses [spatie/dropbox-api](https://github.com/spatie/dropbox-api) and [thephpleague/oauth2-client](https://github.com/thephpleague/oauth2-client)

**Comment by alexkuc** [comment]
So apparently this task is a big harder than looked on the surface but I have made a simple example here - https://github.com/alexkuc/dropbox-oauth2-example. Hopefully it helps someone!

**Comment by GDmac** [comment]
Nice example @alexkuc. For our project we don't need user/visitor permission. 
Our app only needs to fetch things from its own dropbox, so only needs its own token (and refresh-token).

Yes, `Spatie\Dropbox\Client` should probably accept `Guzzle\ClientInterface` (instead of the implementation itself).

Some thoughts:
- The token is valid for 4 hours (14400 secs). 
   Our worker/action takes some time, So we like the token not to expire within next 5 mins (300 sec.) 
   `if (token->getExpires() + 300 <= time()) $token = TokenService->fetchAndStoreNewToken();`
- Maybe an option for a new kind of Spatie\Dropbox\Client could be a version which accepts a 
   simple `interface TokenService`, and is called before each request `tokenService->getToken()`.
   The tokenService should handle expiration, refresh and returning the access-token string.

**Comment by alexkuc** [comment]
> Maybe an option for a new kind of Spatie\Dropbox\Client could be a version which accepts a
simple interface TokenService, and is called before each request tokenService->getToken().
The tokenService should handle expiration, refresh and returning the access-token string.

https://github.com/spatie/dropbox-api/blob/35e5f546bc4c29df34afa7363086dfcfa3448367/src/Client.php#L696

If you have the access token, you can supply it via this method.

If you are looking for a library with tokens support (regular, not refresh ones), there is https://github.com/kunalvarma05/dropbox-php-sdk but it also does not support refresh tokens, so you would need to modify it too.

**Comment by freekmurze** [comment]
We'll continue this in #76
