### ISSUE TITLE
Bad Request

### ISSUE THREAD

**Issue by andrew-webcomsystem** [spatie/dropbox-api#78]
Hello

we are getting Spatie\Dropbox\Exceptions\BadRequest issue while uploading file into dropbox.

We are using latest version of package and 7.4 PHP version.

**Comment by freekmurze** [comment]
I'm not getting any similar reports, so I'm thinking it's something wrong on your end and not a bug in the package. If you are still having problems, please open up a discussion in the Q&A category.
